"""
Reference data for the intake interview: what kind of service this is, and what drives its
cost.

GENERATED by ``agents/build_intake_knowledge.py`` — edit that script or the source documents, not
this file.

    TAXONOMY   from VF-Egypt-Local-Services-Category-Tree.md
    FAMILIES   from Cost Driver Library (1).docx

Why this is code rather than a retrieval index: the whole library is about 12,000 tokens and
the interview needs exactly one family out of thirty-four, chosen deterministically from a
classification the model has already committed to. A vector store would answer the same
question less reliably, need rebuilding whenever the library is revised, and put an
embedding call on the critical path of every turn. Classification picks the family; the
family's driver list goes into the prompt whole.

The spine is the routing decision this file exists to support. From the Cost Driver
Library, Part 3: "Getting this wrong is the commonest failure: running a full FTE build-up
on a celebrity endorsement produces a confident, meaningless number."
"""

from __future__ import annotations

from typing import NamedTuple


class Family(NamedTuple):
    """One cost-driver family from the library."""

    code: str
    name: str
    unit: str
    spine: str
    structure: str
    drivers: str


class Category(NamedTuple):
    """One L2 subcategory of the local services tree."""

    code: str
    l1: str
    l2: str
    spine: str
    families: tuple[str, ...]
    lines: tuple[str, ...]


#: Every cost-driver family in the library, keyed by code.
FAMILIES = {
    'C1': Family(
        code='C1',
        name='Network field O&M',
        unit='Cost per site per month',
        spine='labour',
        structure='Labour 40-50%, fleet and travel 20-30%, spares 10-15%, overhead and margin 20%',
        drivers='Number of sites; site dispersion (sites per cluster, km between sites); preventive maintenance visits per site per year; corrective ticket rate per site per year; MTTR and SLA tier; access difficulty; 24x7 versus 8x5 coverage; technology mix (2G/3G/4G/5G, microwave versus fibre backhaul); spare parts policy; vehicles per team.',
    ),
    'C2': Family(
        code='C2',
        name='Tower and site services',
        unit='Cost per site or per lease',
        spine='labour',
        structure='Labour 35-45%, legal and permits 15-25%, travel 15%, overhead and margin 20-25%',
        drivers='Ground versus rooftop; lease negotiation cycle time; landlord payment escalation; municipal permit lead time and cost; structural analysis; site sharing and colocation administration; legal and registration fees; governorate variation.',
    ),
    'C3': Family(
        code='C3',
        name='Power and energy services',
        unit='Cost per site per month; cost per kWh',
        spine='labour',
        structure='Fuel can exceed 50%; labour 15-25%; spares 10-15%',
        drivers='Grid availability hours; generator run hours and specific consumption in litres per kWh; fuel price and its step changes; fuel logistics distance and pilferage; genset preventive maintenance interval and overhaul cycle; battery bank replacement cycle; solar hybrid capex and diesel offset; rectifier and air-conditioning load; site power draw by technology; remote monitoring availability.',
    ),
    'C4': Family(
        code='C4',
        name='Fibre and transmission',
        unit='Cost per km; per splice; per fault',
        spine='labour',
        structure='Civil works 40-60% on build; labour 30-40% on maintain',
        drivers='Route length and terrain (urban asphalt, desert, agricultural land, canal crossing); trenching versus HDD versus aerial versus microduct; restoration and reinstatement obligation; permit cost per governorate; splice count and splice time; fault rate per 100 km per year - third-party cable cuts dominate in Egypt and must be modelled explicitly; patrol frequency; standby restoration crews and their positioning; OTDR and splicer fleet.',
    ),
    'C5': Family(
        code='C5',
        name='Network rollout and deployment',
        unit='Cost per site delivered; per cluster optimised; per km driven',
        spine='labour',
        structure='Labour 45-55%, plant and lifting 10-20%, travel 15%',
        drivers='Sites per month and the ramp curve; crew productivity in sites per crew per week; rework and acceptance failure rate; tower climbing versus ground work; crane and lifting requirement; integration and script execution; drive test km and post-processing; project management and acceptance documentation overhead; weather and seasonal windows.',
    ),
    'C6': Family(
        code='C6',
        name='NOC / SOC / managed services',
        unit='Cost per monitored element per month; per ticket; per seat',
        spine='labour',
        structure='Labour 60-75%, tools and licences 10-20%, facilities 5-10%',
        drivers='Coverage model - apply the 4.6 to 5.2 FTE per manned 24x7 position rule; alarm volume and correlation ratio; automation and self-healing coverage; L1/L2/L3 skill pyramid; number of managed elements and vendor mix; number of tools and their licences; SLA severity structure; language coverage; disaster recovery site.',
    ),
    'C7': Family(
        code='C7',
        name='IT and digital services',
        unit='Cost per man-day; per story point; per environment per month',
        spine='labour',
        structure='Labour 70-85%, licences and cloud 10-20%',
        drivers='Seniority mix; onshore Cairo versus offshore; environment count and cloud consumption; licence stack; security and compliance certification (ISO 27001, PCI-DSS); ramp and knowledge-transfer period; blended rate versus role-based rate card.',
    ),
    'C8': Family(
        code='C8',
        name='Customer care and contact centre',
        unit='Cost per agent-hour; per contact; per resolved case',
        spine='labour',
        structure='Labour 65-75%, facilities 10-15%, technology 8-12%',
        drivers='Contact volume by channel and interval; average handling time; service level target via Erlang C; shrinkage of 28-35%; occupancy; attrition and retraining cost; language and dialect; seat ratio for multi-shift; WFM, QA and recording licences; telephony and connectivity; digital deflection rate; peak seasonality around Ramadan, offer launches and price changes.',
    ),
    'C9': Family(
        code='C9',
        name='Retail, channel and field sales',
        unit='Cost per store per month; per promoter-day; per activation',
        spine='labour',
        structure='Labour 55-70%, facilities 15-25%, incentives 10-15%',
        drivers='Store count and format; footfall-driven staffing per shift; mall trading hours, which are long and drive the coverage multiplier; promoter and merchandiser day rates; commission and incentive structure; territory size and travel for field sales; point-of-sale materials; mystery shopping and audit frequency; stock and cash handling controls.',
    ),
    'C10': Family(
        code='C10',
        name='Logistics, warehousing and last mile',
        unit='Cost per order; per delivery; per pallet; per m2 per month',
        spine='labour',
        structure='Fleet and fuel 30-40%, labour 30-40%, facilities 15-20%',
        drivers='Order volume and profile (SIM versus device versus network equipment); delivery density and drops per route per day; failed delivery rate; cash-on-delivery handling and reconciliation; reverse logistics and returns; warehouse area, throughput and pick lines per hour; WMS; stock insurance; vehicle type mix; fuel; governorate coverage and rural surcharge.',
    ),
    'C11': Family(
        code='C11',
        name='Facilities management, security and soft services',
        unit='Cost per m2 per month; per guard post per month',
        spine='labour',
        structure='Labour 70-85%',
        drivers='Guard posts multiplied by the 24x7 coverage factor - a single continuously manned post needs about 4.5 to 5 guards; armed versus unarmed; cleaning area and frequency; HVAC and lift maintenance contracts; utilities; pest control; catering headcount and meals per day; staff transport routes.',
    ),
    'C12': Family(
        code='C12',
        name='Marketing, BTL and events',
        unit='Cost per activation-day; per event; per promoter-day',
        spine='labour',
        structure='Production 30-45%, labour 30-40%, logistics 15%',
        drivers='Number of activation days and locations; crew size per activation; production and set build amortised over uses; permits; transport and logistics of assets; agency fee model (retainer, percentage of spend, or FTE-based); seasonality clustering around Ramadan and back-to-school.',
    ),
    'C13': Family(
        code='C13',
        name='Consulting, professional, audit and legal',
        unit='Cost per man-day by grade',
        spine='labour',
        structure='Labour 80-90%, travel and expenses 5-15%',
        drivers='Grade pyramid and blended rate; onsite versus remote days; travel and expenses policy; deliverable count and review cycles; expenses cap; success fee elements.',
    ),
    'C14': Family(
        code='C14',
        name='Outsourced manpower and staff augmentation',
        unit='Cost per FTE per month',
        spine='labour',
        structure='Labour 85-92%, agency fee 8-15%',
        drivers='The full Step 5 employment cost stack passed through, plus the agency administration fee (typically 8-15% of total employment cost) and its own statutory compliance burden under Labour Law 14/2025; replacement guarantee; payroll processing per head.',
    ),
    'C15': Family(
        code='C15',
        name='Construction and data centre works',
        unit='Cost per m2; per rack; per kW of IT load',
        spine='labour',
        structure='Materials 45-60%, labour 20-30%, plant 10%',
        drivers='Bill-of-quantities-driven materials (steel, cement, cable - commodity and FX linked); labour crews by trade; plant hire; supervision and QA/QC; permits; commissioning and testing; Tier certification; defect liability period provision.',
    ),
    'C16': Family(
        code='C16',
        name='Environmental, e-waste and sustainability',
        unit='Cost per tonne; per site decommissioned',
        spine='labour',
        structure='Transport 30-40%, labour 25-35%, disposal fees 20-30%',
        drivers='Waste volume and classification; licensed contractor availability; transport distance to a licensed facility; documentation and certificate issuance; battery and hazardous waste handling; scrap recovery credit, which is a negative cost line and must be captured.',
    ),
    'D1': Family(
        code='D1',
        name='Recruitment and staffing agency services',
        unit='Cost per hire; % of annual salary',
        spine='transaction',
        structure='',
        drivers='Fee basis - percentage of first-year salary (typically 15-25%) versus fixed fee per hire versus retained search; contingency versus retained; volume tiers and rebates; replacement guarantee period and its scope; time-to-fill and its cost to you in unfilled productivity; role seniority mix; scarcity premium for technical and digital roles; advertising and sourcing costs (included or rebilled); assessment and testing per candidate; background and security screening; offer decline rate, which multiplies the effective cost per accepted hire; RPO variants priced per dedicated recruiter FTE instead.',
    ),
    'D2': Family(
        code='D2',
        name='Payroll and HR outsourcing',
        unit='Cost per payslip per month; per employee per year',
        spine='transaction',
        structure='',
        drivers='Headcount and payslip volume; frequency (monthly, weekly, off-cycle runs); volume tier breaks; implementation and parallel-run cost, which is one-off and often understated; system licence versus service fee split; scope - payroll only, or payroll plus benefits administration, plus social insurance filing, plus end-of-service; statutory filing and compliance responsibility under Labour Law 14/2025; number of legal entities and pay groups; self-service portal licences; data migration; exit and data handback cost; error and correction rate; SLA on payroll accuracy.',
    ),
    'D3': Family(
        code='D3',
        name='Training, learning and development',
        unit='Cost per delegate-day; per course; per certification',
        spine='transaction',
        structure='',
        drivers='Trainer day rate by subject seniority; class size and the minimum viable class; no-show and drop-out rate, which raises effective cost per completion; number of runs per year; venue (internal versus hotel) and catering; materials and licensing per delegate; certification and exam fees; translation and Arabic localisation of content; travel for trainer or delegates; e-learning platform licence per user versus per course; content development cost amortised over cohorts; refresher cycle; assessment and post-training evaluation.',
    ),
    'D4': Family(
        code='D4',
        name='Celebrity, talent and endorsement',
        unit='Total deal value; cost per campaign; cost per usage-year',
        spine='rights',
        structure='',
        drivers='Talent tier and reach (local, regional pan-Arab, international); fee for services (shoot days, appearances) held SEPARATE from the usage or licence fee, which is where the real cost sits; media rights granted - TV, digital, OOH, print, in-store, internal use; territory (Egypt only versus MENA versus worldwide); term in months and the renewal or extension rate agreed up front; exclusivity, and category exclusivity in particular, which is the single largest price multiplier; number of shoot days and appearance days, plus overtime rates; agent or agency commission (typically 10-20%); image rights and archive usage after term; morality and reputation clauses and the cost of a replacement scenario; travel, hospitality and rider costs; withholding tax treatment on talent payments; approval rounds and reshoot liability.',
    ),
    'D5': Family(
        code='D5',
        name='Influencer and creator marketing',
        unit='Cost per post; per campaign; effective CPM',
        spine='rights',
        structure='',
        drivers='Creator tier by follower count and engagement rate rather than follower count alone; deliverable mix (feed post, story, reel, long-form video, live); usage rights - whether you may reuse the content as paid media, and for how long, which is frequently priced separately and forgotten; exclusivity window; number of revisions; whitelisting and paid amplification budget; platform mix; agency or network commission; disclosure and compliance requirements; fraud and fake-engagement risk; measurement and verification tooling.',
    ),
    'D6': Family(
        code='D6',
        name='Advertising production',
        unit='Cost per asset; per production day',
        spine='deliverable',
        structure='',
        drivers='Format (TVC, digital film, static, audio, animation); number of shoot days and crew size; director tier; location versus studio, and permits for public locations in Egypt; cast - principals versus extras, and their usage buyouts, which recur like talent rights; set build and props; post-production (edit, grade, VFX, sound design); music - original composition versus licensed track, and its own territory and term; number of versions, cuts and language variants; Arabic and dialect versioning; revision rounds; travel and per diem for crew; equipment hire; contingency and weather days.',
    ),
    'D7': Family(
        code='D7',
        name='Media planning and buying',
        unit='Cost per GRP; per CPM; agency fee as % of billings',
        spine='passthrough',
        structure='',
        drivers='Gross versus net media rates and where discounts land; agency commission basis - percentage of billings versus fixed fee versus FTE-based retainer, which is the whole negotiation; TV cost per point and channel mix; digital CPM, CPC and viewability standards; OOH site rates by location and duration; RAMADAN PREMIUM, which materially multiplies Egyptian TV rates and must be modelled as its own line rather than smoothed across the year; seasonality beyond Ramadan (back-to-school, Eid, summer coast); make-goods and under-delivery remedies; ad-serving and trafficking fees; brand safety and verification fees; production versus media split; volume commitments and annual rebates.',
    ),
    'D8': Family(
        code='D8',
        name='Creative agency and brand services',
        unit='Cost per project; per man-day by grade; annual retainer',
        spine='deliverable',
        structure='',
        drivers='Fee model - retainer versus project versus FTE-based scope of work; grade pyramid and blended day rate; number of campaigns and assets per year; revision and review rounds, which are the commonest source of overrun; strategy versus execution split; brand guideline and identity work as one-off; localisation and Arabic adaptation; pitch and onboarding cost; performance-linked fee elements; third-party pass-throughs and the handling fee on them.',
    ),
    'D9': Family(
        code='D9',
        name='Public relations and corporate communications',
        unit='Monthly retainer; cost per event; per release',
        spine='deliverable',
        structure='',
        drivers='Retainer scope and named team seniority; number of releases, briefings and events per year; media monitoring and clipping service; crisis retainer and stand-by availability; spokesperson training; executive profiling; regional versus local coverage; content production; translation; measurement and share-of-voice reporting; out-of-scope hourly rates, which is where retainers leak.',
    ),
    'D10': Family(
        code='D10',
        name='Market research and consumer insight',
        unit='Cost per interview; per wave; per study',
        spine='transaction',
        structure='',
        drivers='Methodology (CATI, CAPI, online panel, focus group, ethnographic); sample size and incidence rate, which drives screening cost far more than sample size does; number of waves and their frequency; questionnaire length; geographic spread and rural fieldwork premium; panel incentive per respondent; translation and dialect handling; recruitment difficulty for niche audiences; analysis and reporting depth; tracker versus ad-hoc; data ownership and reuse rights.',
    ),
    'D11': Family(
        code='D11',
        name='Events, sponsorship and rights',
        unit='Total rights fee; cost per attendee; per activation day',
        spine='rights',
        structure='',
        drivers='Rights fee held separate from activation spend, with a rule of thumb that activation costs at least as much again as the rights; category exclusivity; term and renewal option pricing; assets granted (branding, hospitality, IP usage, player or artist access); territory; activation production and staffing; venue and permits; hospitality and guest volume; talent appearance fees within the sponsorship; measurement and valuation of exposure; termination and force majeure exposure.',
    ),
    'D12': Family(
        code='D12',
        name='Legal, tax and regulatory advisory',
        unit='Cost per man-day by grade; per matter; annual retainer',
        spine='deliverable',
        structure='',
        drivers='Partner, associate and paralegal mix and the blended effective rate; hourly versus fixed fee per matter versus retainer; matter volume and complexity mix; local counsel versus international firm; disbursements and court fees; translation and notarisation, which are material in Egypt; regulatory filing fees; success or contingency elements; conflict-check and onboarding; out-of-hours and urgent-turnaround premiums.',
    ),
    'D13': Family(
        code='D13',
        name='Audit, assurance and financial advisory',
        unit='Cost per man-day by grade; per engagement',
        spine='deliverable',
        structure='',
        drivers='Scope (statutory audit, internal audit, IT audit, SOX-type controls, due diligence); grade pyramid and hours per grade; number of entities and locations in scope; first-year premium versus recurring years; specialist input (tax, valuation, IT); travel; out-of-scope change requests; regulatory deadline pressure and its overtime cost.',
    ),
    'D14': Family(
        code='D14',
        name='Business process outsourcing (non-voice)',
        unit='Cost per transaction; per FTE per month',
        spine='transaction',
        structure='',
        drivers='Transaction volume and mix; average handling time per transaction type; accuracy SLA and rework rate; automation and straight-through-processing share, which should reduce unit cost over the term - build the reduction into the price curve rather than leaving it as vendor upside; shift coverage; skill tier; system access and licence cost; transition and knowledge transfer; volume bands and minimum commitment; gain-share on productivity.',
    ),
    'D15': Family(
        code='D15',
        name='Corporate services and facilities-adjacent',
        unit='Varies by service',
        spine='',
        structure='',
        drivers='Travel management (transaction fee per booking versus percentage of spend; online adoption rate; after-hours support; savings guarantee); catering (meals per day, headcount, menu tier, subsidy split); printing and document management (cost per page, device fleet, click charges, volume commitment); translation (per word rate by language pair and subject, certified versus standard, urgency premium, repetition and translation-memory discount); insurance brokerage (commission versus fee, placed premium, claims handling); fleet management (see C1 fleet drivers); relocation and mobility (per assignee package).',
    ),
    'D16': Family(
        code='D16',
        name='Content, licensing and digital services',
        unit='Cost per subscriber; per stream; minimum guarantee',
        spine='rights',
        structure='',
        drivers='Licence structure - minimum guarantee versus revenue share versus per-subscriber-per-month; term and territory; exclusivity; content volume and refresh rate; platform and delivery cost; A2P SMS and aggregation rates per message with volume tiers; API and integration cost; content moderation; localisation and subtitling; rights renewal risk at end of term.',
    ),
}


#: Every L2 subcategory of the local services tree, in document order.
CATEGORIES = (
    Category(
        code='1.1',
        l1='1. Network deployment and civil works',
        l2='Site acquisition and leasing services',
        spine='labour',
        families=('C2',),
        lines=('Site search, survey and candidate identification', 'Landlord negotiation and lease documentation', 'Municipal and governorate permitting', 'Site registration, notarisation and legal filing', 'Lease renewal and rent review administration', 'Site sharing and colocation coordination with TowerCos'),
    ),
    Category(
        code='1.2',
        l1='1. Network deployment and civil works',
        l2='Civil works and site build',
        spine='labour',
        families=('C15',),
        lines=('Greenfield tower foundation and erection', 'Rooftop steelwork, mounting poles and reinforcement', 'Shelter and cabinet installation', 'Fencing, access roads, earthing and lightning protection', 'Site restoration and reinstatement', 'Structural analysis and load certification'),
    ),
    Category(
        code='1.3',
        l1='1. Network deployment and civil works',
        l2='RAN installation and commissioning',
        spine='labour',
        families=('C5',),
        lines=('Antenna and radio unit installation', 'Tower climbing and rigging services', 'Feeder, jumper and cabling works', 'Integration, script execution and node commissioning', 'Site acceptance testing and documentation', 'Crane and heavy lifting services'),
    ),
    Category(
        code='1.4',
        l1='1. Network deployment and civil works',
        l2='Network optimisation and drive testing',
        spine='labour',
        families=('C5',),
        lines=('Cluster and single-site optimisation', 'Drive test and walk test execution', 'Benchmarking against competitor networks', 'Post-processing, analysis and reporting', 'Indoor coverage survey and DAS design'),
    ),
    Category(
        code='1.5',
        l1='1. Network deployment and civil works',
        l2='Site decommissioning and swap',
        spine='labour',
        families=('C5', 'C16'),
        lines=('Technology swap and modernisation execution', 'Site dismantling and equipment recovery', 'Asset return, refurbishment and scrap disposal', 'Landlord handback and site restoration'),
    ),
    Category(
        code='2.1',
        l1='2. Network operations and maintenance',
        l2='Field preventive and corrective maintenance',
        spine='labour',
        families=('C1',),
        lines=('Scheduled preventive maintenance visits', 'Fault response and corrective maintenance', 'Emergency and escalation call-out', 'Site cleaning, housekeeping and vegetation control', 'Spare parts logistics to site'),
    ),
    Category(
        code='2.2',
        l1='2. Network operations and maintenance',
        l2='Managed services and network outsourcing',
        spine='labour',
        families=('C6',),
        lines=('Full managed services for RAN, core or transport', 'Field force outsourcing with SLA', 'Vendor-managed maintenance under OEM contract', 'Performance and SLA reporting services'),
    ),
    Category(
        code='2.3',
        l1='2. Network operations and maintenance',
        l2='Network operations centre',
        spine='labour',
        families=('C6',),
        lines=('24x7 monitoring and first-line response', 'Second and third line technical support', 'Change management and configuration control', 'Capacity and performance management', 'Disaster recovery and business continuity services'),
    ),
    Category(
        code='2.4',
        l1='2. Network operations and maintenance',
        l2='Test, measurement and calibration',
        spine='transaction',
        families=('C1',),
        lines=('Instrument calibration and certification', 'Test equipment rental and hire', 'Repair and refurbishment of test tools'),
    ),
    Category(
        code='2.5',
        l1='2. Network operations and maintenance',
        l2='Tower company interface services',
        spine='deliverable',
        families=('C2',),
        lines=('Colocation order management and coordination', 'SLA monitoring and dispute resolution support', 'Site audit and reconciliation against TowerCo billing'),
    ),
    Category(
        code='3.1',
        l1='3. Energy and power services',
        l2='Generator services',
        spine='labour',
        families=('C3',),
        lines=('Preventive maintenance and overhaul', 'Emergency repair and standby generator hire', 'Generator installation, relocation and removal'),
    ),
    Category(
        code='3.2',
        l1='3. Energy and power services',
        l2='Fuel supply and management',
        spine='passthrough',
        families=('C3',),
        lines=('Diesel supply and delivery to sites', 'Fuel monitoring, metering and reconciliation', 'Fuel theft investigation and loss control', 'Tank installation, cleaning and disposal'),
    ),
    Category(
        code='3.3',
        l1='3. Energy and power services',
        l2='Power systems maintenance',
        spine='labour',
        families=('C3',),
        lines=('Rectifier, DC plant and UPS maintenance', 'Battery testing, replacement and disposal', 'Cooling and air conditioning maintenance', 'Electrical safety inspection and certification'),
    ),
    Category(
        code='3.4',
        l1='3. Energy and power services',
        l2='Renewable and energy efficiency',
        spine='deliverable',
        families=('C3',),
        lines=('Solar hybrid design, installation and O&M', 'Energy audit and efficiency consultancy', 'Free cooling and equipment upgrade programmes', 'Carbon and energy reporting services'),
    ),
    Category(
        code='3.5',
        l1='3. Energy and power services',
        l2='Grid connection services',
        spine='passthrough',
        families=('C3',),
        lines=('Utility connection application and follow-up', 'Meter installation, upgrade and relocation', 'Electricity consumption reconciliation and dispute handling'),
    ),
    Category(
        code='4.1',
        l1='4. Fibre, transmission and fixed network',
        l2='Fibre network build',
        spine='labour',
        families=('C4',),
        lines=('Route survey and design', 'Trenching, HDD and duct installation', 'Aerial fibre deployment', 'Cable pulling, splicing and termination', 'Reinstatement and restoration works', 'As-built documentation and GIS update'),
    ),
    Category(
        code='4.2',
        l1='4. Fibre, transmission and fixed network',
        l2='Fibre maintenance and restoration',
        spine='labour',
        families=('C4',),
        lines=('Preventive patrol and route surveillance', 'Emergency fault restoration and standby crews', 'Third-party cable cut investigation and claims', 'OTDR testing and route certification'),
    ),
    Category(
        code='4.3',
        l1='4. Fibre, transmission and fixed network',
        l2='Microwave and transmission services',
        spine='labour',
        families=('C1',),
        lines=('Link installation, alignment and commissioning', 'Transmission maintenance and fault resolution', 'Frequency coordination and licensing support'),
    ),
    Category(
        code='4.4',
        l1='4. Fibre, transmission and fixed network',
        l2='Duct, right of way and wayleave services',
        spine='passthrough',
        families=('C2',),
        lines=('Right-of-way negotiation with authorities', 'Duct lease and infrastructure sharing administration', 'Crossing permits for roads, rail, canals and utilities'),
    ),
    Category(
        code='5.1',
        l1='5. IT, digital and data services',
        l2='Application development and integration',
        spine='deliverable',
        families=('C7',),
        lines=('Custom development and enhancement', 'System integration and API development', 'Legacy migration and modernisation', 'Low-code and automation development'),
    ),
    Category(
        code='5.2',
        l1='5. IT, digital and data services',
        l2='Application support and maintenance',
        spine='labour',
        families=('C7',),
        lines=('L1, L2 and L3 application support', 'Managed application services', 'Database administration and tuning'),
    ),
    Category(
        code='5.3',
        l1='5. IT, digital and data services',
        l2='Testing and quality assurance',
        spine='deliverable',
        families=('C7',),
        lines=('Functional and regression testing', 'Performance and load testing', 'Test automation development', 'User acceptance testing support'),
    ),
    Category(
        code='5.4',
        l1='5. IT, digital and data services',
        l2='Infrastructure and cloud services',
        spine='transaction',
        families=('C7',),
        lines=('Data centre operations and hosting', 'Cloud migration and managed cloud', 'Backup, storage and disaster recovery', 'End-user computing and service desk'),
    ),
    Category(
        code='5.5',
        l1='5. IT, digital and data services',
        l2='Data, analytics and AI services',
        spine='deliverable',
        families=('C7',),
        lines=('Data engineering and pipeline development', 'BI and reporting development', 'Data science, modelling and AI use cases', 'Data quality and governance services'),
    ),
    Category(
        code='5.6',
        l1='5. IT, digital and data services',
        l2='Digital channel services',
        spine='deliverable',
        families=('C7',),
        lines=('App and web development and maintenance', 'UX and UI design services', 'Digital content management and publishing', 'Accessibility and localisation testing'),
    ),
    Category(
        code='6.1',
        l1='6. Cybersecurity, risk and compliance',
        l2='Security operations',
        spine='labour',
        families=('C6',),
        lines=('SOC monitoring and incident response', 'Threat intelligence and hunting services', 'Vulnerability management and patch coordination'),
    ),
    Category(
        code='6.2',
        l1='6. Cybersecurity, risk and compliance',
        l2='Security assessment services',
        spine='deliverable',
        families=('C7',),
        lines=('Penetration testing and red teaming', 'Security architecture review', 'Application and code security review', 'Third-party and supplier security assessment'),
    ),
    Category(
        code='6.3',
        l1='6. Cybersecurity, risk and compliance',
        l2='Compliance and certification',
        spine='deliverable',
        families=('D13',),
        lines=('ISO 27001, PCI-DSS and related certification', 'Audit readiness and remediation support', 'Privacy and data protection assessment'),
    ),
    Category(
        code='6.4',
        l1='6. Cybersecurity, risk and compliance',
        l2='Physical and technical security systems',
        spine='labour',
        families=('C11',),
        lines=('CCTV, access control and alarm maintenance', 'Site intrusion detection and monitoring', 'Security system design and installation'),
    ),
    Category(
        code='7.1',
        l1='7. Customer operations and service',
        l2='Contact centre outsourcing',
        spine='labour',
        families=('C8',),
        lines=('Inbound voice customer service', 'Outbound telesales and retention', 'Digital and social channel handling', 'Back-office and non-voice processing', 'Dedicated business and enterprise support desks'),
    ),
    Category(
        code='7.2',
        l1='7. Customer operations and service',
        l2='Field customer services',
        spine='labour',
        families=('C1',),
        lines=('Fixed and FWA installation at customer premises', 'In-home service visits and fault resolution', 'Enterprise on-site support'),
    ),
    Category(
        code='7.3',
        l1='7. Customer operations and service',
        l2='Customer experience services',
        spine='deliverable',
        families=('D10',),
        lines=('Mystery shopping and service audits', 'Customer satisfaction and NPS measurement', 'Quality monitoring and call auditing', 'Customer journey design consultancy'),
    ),
    Category(
        code='7.4',
        l1='7. Customer operations and service',
        l2='Collections and credit services',
        spine='transaction',
        families=('D14',),
        lines=('Early and late-stage collections', 'Debt recovery and legal collections support', 'Credit scoring and fraud screening services'),
    ),
    Category(
        code='7.5',
        l1='7. Customer operations and service',
        l2='Business process outsourcing',
        spine='transaction',
        families=('D14',),
        lines=('Order management and provisioning', 'Billing operations and dispute handling', 'Document and records processing', 'Revenue assurance support'),
    ),
    Category(
        code='8.1',
        l1='8. Retail, channel and sales services',
        l2='Retail operations services',
        spine='labour',
        families=('C9',),
        lines=('Outsourced store staffing and promoters', 'Store cleaning, maintenance and soft services', 'Queue management and greeter services'),
    ),
    Category(
        code='8.2',
        l1='8. Retail, channel and sales services',
        l2='Store build and fit-out',
        spine='deliverable',
        families=('C15',),
        lines=('Store design and space planning', 'Fit-out, refurbishment and relocation', 'Signage, fascia and illuminated branding', 'Furniture, fixtures and display manufacture'),
    ),
    Category(
        code='8.3',
        l1='8. Retail, channel and sales services',
        l2='Channel and distribution support',
        spine='labour',
        families=('C9',),
        lines=('Field sales and territory coverage teams', 'Dealer and retailer visit programmes', 'Merchandising and planogram execution', 'Trade audit and distribution measurement'),
    ),
    Category(
        code='8.4',
        l1='8. Retail, channel and sales services',
        l2='Direct and door-to-door sales',
        spine='transaction',
        families=('C9',),
        lines=('Residential fixed and FWA acquisition teams', 'Event-based and kiosk sales', 'B2B lead generation and appointment setting'),
    ),
    Category(
        code='9.1',
        l1='9. Logistics, warehousing and fleet',
        l2='Warehousing services',
        spine='labour',
        families=('C10',),
        lines=('Third-party warehouse operation', 'Inventory management and cycle counting', 'Kitting, bundling and value-added services', 'Bonded and customs warehousing'),
    ),
    Category(
        code='9.2',
        l1='9. Logistics, warehousing and fleet',
        l2='Transport and distribution',
        spine='transaction',
        families=('C10',),
        lines=('Inbound and outbound freight, domestic', 'Site delivery of network equipment', 'SIM, device and accessory distribution to channel', 'Reverse logistics and returns handling'),
    ),
    Category(
        code='9.3',
        l1='9. Logistics, warehousing and fleet',
        l2='Last-mile and courier services',
        spine='transaction',
        families=('C10',),
        lines=('E-commerce and direct-to-customer delivery', 'Cash on delivery handling and reconciliation', 'Document and SIM courier services'),
    ),
    Category(
        code='9.4',
        l1='9. Logistics, warehousing and fleet',
        l2='Customs and freight forwarding',
        spine='passthrough',
        families=('C10',),
        lines=('Customs clearance and brokerage', 'Import documentation and duty handling', 'Port storage and demurrage management'),
    ),
    Category(
        code='9.5',
        l1='9. Logistics, warehousing and fleet',
        l2='Fleet services',
        spine='transaction',
        families=('C1',),
        lines=('Vehicle leasing and rental', 'Fleet maintenance and repair', 'Driver provision and outsourcing', 'Fuel card management and telematics', 'Vehicle branding and de-branding'),
    ),
    Category(
        code='10.1',
        l1='10. Marketing, brand and communications',
        l2='Creative and brand agency services',
        spine='deliverable',
        families=('D8',),
        lines=('Creative concept and campaign development', 'Brand strategy and identity work', 'Copywriting, art direction and adaptation', 'Arabic and dialect localisation'),
    ),
    Category(
        code='10.2',
        l1='10. Marketing, brand and communications',
        l2='Advertising production',
        spine='deliverable',
        families=('D6',),
        lines=('TVC and digital film production', 'Photography and still content shoots', 'Audio, radio and jingle production', 'Animation, motion graphics and VFX', 'Music composition and licensing'),
    ),
    Category(
        code='10.3',
        l1='10. Marketing, brand and communications',
        l2='Media planning and buying',
        spine='passthrough',
        families=('D7',),
        lines=('TV, radio and print media buying', 'Digital and programmatic media', 'Out-of-home and transit advertising', 'Ramadan and peak-season inventory', 'Ad serving, verification and brand safety'),
    ),
    Category(
        code='10.4',
        l1='10. Marketing, brand and communications',
        l2='Digital and performance marketing',
        spine='passthrough',
        families=('D7',),
        lines=('Search, social and display performance campaigns', 'SEO and content marketing services', 'Marketing automation and CRM campaign execution', 'Affiliate and lead generation'),
    ),
    Category(
        code='10.5',
        l1='10. Marketing, brand and communications',
        l2='Below the line and activation',
        spine='labour',
        families=('C12',),
        lines=('Roadshows, activations and sampling', 'Promoter staffing for campaigns', 'Kiosk and stand production and operation', 'University, school and community programmes'),
    ),
    Category(
        code='10.6',
        l1='10. Marketing, brand and communications',
        l2='Public relations and corporate communications',
        spine='deliverable',
        families=('D9',),
        lines=('PR retainer and media relations', 'Media monitoring and clipping', 'Crisis communications and spokesperson training', 'Internal communications and employee campaigns', 'Executive profiling and thought leadership'),
    ),
    Category(
        code='10.7',
        l1='10. Marketing, brand and communications',
        l2='Printing and production',
        spine='transaction',
        families=('D15',),
        lines=('POS materials, brochures and leaflets', 'Large format printing and banners', 'Packaging, SIM packs and scratch cards', 'Corporate stationery and forms'),
    ),
    Category(
        code='10.8',
        l1='10. Marketing, brand and communications',
        l2='Promotional merchandise',
        spine='transaction',
        families=('D15',),
        lines=('Branded giveaways and corporate gifts', 'Uniforms and staff clothing', 'Event and campaign merchandise'),
    ),
    Category(
        code='11.1',
        l1='11. Talent, sponsorship and content rights',
        l2='Celebrity and talent engagement',
        spine='rights',
        families=('D4',),
        lines=('Brand ambassador and endorsement deals', 'Campaign talent and appearance fees', 'Voiceover and presenter talent', 'Extras and background casting'),
    ),
    Category(
        code='11.2',
        l1='11. Talent, sponsorship and content rights',
        l2='Influencer and creator marketing',
        spine='rights',
        families=('D5',),
        lines=('Influencer campaign contracting', 'Creator content production and usage rights', 'Influencer network and agency services'),
    ),
    Category(
        code='11.3',
        l1='11. Talent, sponsorship and content rights',
        l2='Sponsorship and rights',
        spine='rights',
        families=('D11',),
        lines=('Sports team, league and event sponsorship', 'Music, arts and cultural sponsorship', 'Ramadan drama sponsorship and product placement', 'Conference and industry event sponsorship', 'CSR and community programme sponsorship'),
    ),
    Category(
        code='11.4',
        l1='11. Talent, sponsorship and content rights',
        l2='Content and licensing',
        spine='rights',
        families=('D16',),
        lines=('Music, video and gaming content licensing for VAS', 'Sports and entertainment content rights', 'Stock imagery, footage and font licensing', 'Subtitling, dubbing and localisation'),
    ),
    Category(
        code='11.5',
        l1='11. Talent, sponsorship and content rights',
        l2='Events management',
        spine='deliverable',
        families=('D11',),
        lines=('Corporate and customer events', 'Product and campaign launches', 'Conference and exhibition participation', 'Hospitality programmes and guest management', 'Internal town halls and staff events'),
    ),
    Category(
        code='12.1',
        l1='12. Research, insight and consultancy',
        l2='Market and consumer research',
        spine='transaction',
        families=('D10',),
        lines=('Brand health and tracking studies', 'Concept, product and pricing testing', 'Qualitative research and focus groups', 'Customer segmentation studies', 'Field interviewing and panel services'),
    ),
    Category(
        code='12.2',
        l1='12. Research, insight and consultancy',
        l2='Data and measurement services',
        spine='transaction',
        families=('D10',),
        lines=('Media and audience measurement subscriptions', 'Competitive intelligence and price tracking', 'Mobile network benchmarking (independent)'),
    ),
    Category(
        code='12.3',
        l1='12. Research, insight and consultancy',
        l2='Management consultancy',
        spine='deliverable',
        families=('D13',),
        lines=('Strategy and business model advisory', 'Operating model and organisation design', 'Transformation and change programme support', 'Process improvement and cost optimisation'),
    ),
    Category(
        code='13.1',
        l1='13. People and HR services',
        l2='Recruitment and staffing',
        spine='transaction',
        families=('D1',),
        lines=('Permanent recruitment agency services', 'Executive search', 'Temporary and contract staffing', 'Recruitment process outsourcing', 'Graduate and campus hiring programmes', 'Assessment centres and psychometric testing'),
    ),
    Category(
        code='13.2',
        l1='13. People and HR services',
        l2='Outsourced manpower',
        spine='labour',
        families=('C14',),
        lines=('Payrolled contractor supply', 'Dedicated outsourced teams under VF supervision', 'Seasonal and surge manpower'),
    ),
    Category(
        code='13.3',
        l1='13. People and HR services',
        l2='Payroll and HR administration',
        spine='transaction',
        families=('D2',),
        lines=('Payroll processing and payslip issuance', 'Social insurance filing and compliance', 'HR systems support and administration', 'Employee records and document management'),
    ),
    Category(
        code='13.4',
        l1='13. People and HR services',
        l2='Training and development',
        spine='transaction',
        families=('D3',),
        lines=('Technical and vendor certification training', 'Leadership and soft skills programmes', 'Language training', 'Sales and customer service training', 'E-learning platform and content development', 'Health, safety and compliance training'),
    ),
    Category(
        code='13.5',
        l1='13. People and HR services',
        l2='Employee benefits and wellbeing',
        spine='transaction',
        families=('D15',),
        lines=('Medical insurance brokerage and administration', 'Life and personal accident cover placement', 'Employee assistance and wellbeing programmes', 'Occupational health and medical screening', 'On-site clinic and nursing services'),
    ),
    Category(
        code='13.6',
        l1='13. People and HR services',
        l2='HR advisory services',
        spine='deliverable',
        families=('D13',),
        lines=('Compensation benchmarking and job evaluation', 'Employee engagement survey services', 'Labour law and industrial relations advisory', 'Organisational culture and change support'),
    ),
    Category(
        code='14.1',
        l1='14. Professional, legal and financial services',
        l2='Legal services',
        spine='deliverable',
        families=('D12',),
        lines=('Corporate and commercial legal counsel', 'Litigation and dispute representation', 'Regulatory and telecoms law advisory', 'Labour and employment law', 'Intellectual property and trademark services', 'Notarisation, legalisation and translation of legal documents'),
    ),
    Category(
        code='14.2',
        l1='14. Professional, legal and financial services',
        l2='Tax and regulatory advisory',
        spine='deliverable',
        families=('D12',),
        lines=('Corporate tax advisory and compliance', 'VAT, WHT and transfer pricing support', 'Customs and trade advisory', 'Tax dispute and appeal support'),
    ),
    Category(
        code='14.3',
        l1='14. Professional, legal and financial services',
        l2='Audit and assurance',
        spine='deliverable',
        families=('D13',),
        lines=('Statutory external audit', 'Internal audit co-sourcing', 'IT and controls audit', 'Fraud investigation and forensic services'),
    ),
    Category(
        code='14.4',
        l1='14. Professional, legal and financial services',
        l2='Financial and treasury services',
        spine='transaction',
        families=('D15',),
        lines=('Bank charges, guarantees and letters of credit', 'Insurance brokerage and placement', 'Actuarial and valuation services', 'Debt collection agency services'),
    ),
    Category(
        code='14.5',
        l1='14. Professional, legal and financial services',
        l2='Vodafone Cash and financial services operations',
        spine='transaction',
        families=('D14',),
        lines=('Agent network management and support', 'Cash-in and cash-out logistics', 'KYC verification and onboarding services', 'Transaction dispute and fraud handling', 'Regulatory reporting support to the Central Bank'),
    ),
    Category(
        code='15.1',
        l1='15. Property, facilities and workplace',
        l2='Property services',
        spine='deliverable',
        families=('D15',),
        lines=('Real estate brokerage and lease advisory', 'Property valuation and survey', 'Lease administration and rent review'),
    ),
    Category(
        code='15.2',
        l1='15. Property, facilities and workplace',
        l2='Construction and fit-out',
        spine='deliverable',
        families=('C15',),
        lines=('Office fit-out and refurbishment', 'Data centre construction and upgrade', 'Project management and site supervision', 'MEP design and engineering consultancy'),
    ),
    Category(
        code='15.3',
        l1='15. Property, facilities and workplace',
        l2='Hard facilities management',
        spine='labour',
        families=('C11',),
        lines=('HVAC, lift and building systems maintenance', 'Electrical and plumbing maintenance', 'Fire systems inspection and certification', 'Building fabric and general repairs'),
    ),
    Category(
        code='15.4',
        l1='15. Property, facilities and workplace',
        l2='Soft facilities management',
        spine='labour',
        families=('C11',),
        lines=('Cleaning and janitorial services', 'Landscaping and grounds maintenance', 'Pest control', 'Waste collection and general disposal', 'Reception, front-of-house and mailroom'),
    ),
    Category(
        code='15.5',
        l1='15. Property, facilities and workplace',
        l2='Catering and hospitality',
        spine='transaction',
        families=('D15',),
        lines=('Staff canteen operation', 'Meeting and event catering', 'Vending and pantry supplies'),
    ),
    Category(
        code='15.6',
        l1='15. Property, facilities and workplace',
        l2='Manned security',
        spine='labour',
        families=('C11',),
        lines=('Static guarding at offices, warehouses and stores', 'Site and technical facility guarding', 'Escort services for high-risk areas', 'Executive protection and risk assessment'),
    ),
    Category(
        code='15.7',
        l1='15. Property, facilities and workplace',
        l2='Employee transport',
        spine='transaction',
        families=('C11',),
        lines=('Staff bussing and shift transport', 'Executive car services', 'Contact centre night transport'),
    ),
    Category(
        code='16.1',
        l1='16. Sustainability, HSE and environmental',
        l2='Health and safety services',
        spine='deliverable',
        families=('C11',),
        lines=('HSE consultancy and audit', 'Safety officer provision on projects', 'Incident investigation and root cause analysis', 'Working at height and rescue training', 'PPE supply and certification'),
    ),
    Category(
        code='16.2',
        l1='16. Sustainability, HSE and environmental',
        l2='Environmental services',
        spine='transaction',
        families=('C16',),
        lines=('Environmental impact assessment', 'Emissions monitoring and reporting', 'EMF and radiation compliance measurement', 'Environmental permit management'),
    ),
    Category(
        code='16.3',
        l1='16. Sustainability, HSE and environmental',
        l2='Waste and e-waste management',
        spine='transaction',
        families=('C16',),
        lines=('Electronic and network equipment disposal', 'Battery and hazardous waste handling', 'Scrap sale and recovery', 'Certificate of destruction and documentation'),
    ),
    Category(
        code='16.4',
        l1='16. Sustainability, HSE and environmental',
        l2='Sustainability reporting and advisory',
        spine='deliverable',
        families=('D13',),
        lines=('ESG reporting and assurance', 'Carbon footprint measurement', 'Circular economy and take-back programme design'),
    ),
    Category(
        code='17.1',
        l1='17. Travel, corporate and shared services',
        l2='Travel management',
        spine='passthrough',
        families=('D15',),
        lines=('Corporate travel agency services', 'Hotel programme negotiation and booking', 'Visa and travel documentation support', 'Ground transport and airport services'),
    ),
    Category(
        code='17.2',
        l1='17. Travel, corporate and shared services',
        l2='Translation and language services',
        spine='transaction',
        families=('D15',),
        lines=('Document translation, Arabic and English', 'Certified and legal translation', 'Simultaneous and consecutive interpretation', 'Subtitling and transcription'),
    ),
    Category(
        code='17.3',
        l1='17. Travel, corporate and shared services',
        l2='Document and print management',
        spine='transaction',
        families=('D15',),
        lines=('Managed print services and device fleet', 'Document scanning and digitisation', 'Secure document storage and archiving', 'Confidential document destruction'),
    ),
    Category(
        code='17.4',
        l1='17. Travel, corporate and shared services',
        l2='Corporate subscriptions and memberships',
        spine='transaction',
        families=('D15',),
        lines=('Industry association memberships', 'Research and data subscriptions', 'Professional body fees and licences'),
    ),
    Category(
        code='18.1',
        l1='18. Regulatory and external affairs support',
        l2='Regulatory support services',
        spine='deliverable',
        families=('D12',),
        lines=('NTRA filing and licensing support', 'Spectrum and frequency coordination consultancy', 'Regulatory economics and policy analysis'),
    ),
    Category(
        code='18.2',
        l1='18. Regulatory and external affairs support',
        l2='Government and stakeholder engagement',
        spine='deliverable',
        families=('D9',),
        lines=('Public affairs advisory', 'Stakeholder mapping and engagement programmes', 'Policy research and position papers'),
    ),
    Category(
        code='18.3',
        l1='18. Regulatory and external affairs support',
        l2='Corporate social responsibility delivery',
        spine='deliverable',
        families=('D11',),
        lines=('CSR programme design and implementation', 'NGO and foundation partnership delivery', 'Community and digital inclusion programmes', 'Impact measurement and reporting'),
    ),
)

CATEGORIES_BY_CODE = {c.code: c for c in CATEGORIES}


#: Long names for the five spines, as the Skill Specification writes them. Shown to the
#: analyst when the classification is confirmed, because "labour" alone does not say what
#: is about to happen to their interview.
SPINE_NAMES = {
    "labour": "Labour-built",
    "deliverable": "Deliverable-built",
    "transaction": "Transaction-built",
    "rights": "Rights-built",
    "passthrough": "Pass-through plus fee",
}

#: How each spine builds the cost. Cost Driver Library, Part 3.
SPINE_DESCRIPTIONS = {
    "labour": (
        "Bottom-up from headcount: workload or coverage FTE, then fully loaded employment "
        "cost. The full staffing build applies."
    ),
    "deliverable": (
        "Priced per deliverable, per project or per man-day of a named grade. Staffing is "
        "the vendor's problem, not yours - grade mix and days per deliverable replace FTE."
    ),
    "transaction": (
        "Unit price times volume, with tier breaks: per payslip, per hire, per delegate-day, "
        "per shipment. Headcount only applies to a dedicated on-site team."
    ),
    "rights": (
        "The cost is the licence, not the work: territory, term, exclusivity and channels "
        "granted. Production is a separate line and the headcount build does not apply."
    ),
    "passthrough": (
        "Third-party spend passes through at cost with a commission or handling fee on top. "
        "The fee basis and the gross-versus-net question are the whole negotiation."
    ),
}


def family(code: str) -> Family | None:
    """The library entry for a family code, or None if the code is unknown."""
    return FAMILIES.get((code or "").strip().upper())


def category(code: str) -> Category | None:
    """The tree entry for an L2 code such as "2.3", or None."""
    return CATEGORIES_BY_CODE.get((code or "").strip())


def resolve_spine(category_code: str, family_code: str) -> str:
    """The spine to route on, preferring the tree's tag over the family's.

    The two agree almost everywhere. Where they do not, the tree wins: it tags the specific
    subcategory being bought, while a family's spine is the one that fits most of its
    members. D15 is the clear case - the library records its spine as "Mixed" because
    corporate services span three of them, and only the tree knows that travel management is
    pass-through while translation is transaction-built.
    """
    if entry := category(category_code):
        if entry.spine:
            return entry.spine
    if entry := family(family_code):
        return entry.spine
    return ""


#: Compact index for the classifier prompt: one line per subcategory. Built rather than
#: stored so it cannot drift from the table above.
TAXONOMY_INDEX = "\n".join(
    f"{c.code} {c.l2} [{c.l1}] -> spine={c.spine} family={'/'.join(c.families)}"
    f"  ({'; '.join(c.lines[:4])})"
    for c in CATEGORIES
)


#: Cost categories the analyst will not volunteer and the supplier will not itemise.
#: Cost Driver Library, Part 8. Prompted for explicitly in the closing stage.
OFTEN_OMITTED = {
    "Indirect roles": (
        "Planners and dispatch, QA and audit, HSE officers, trainers, spares controllers, "
        "admin and HR support, service delivery or contract manager, SLA reporting analyst."
    ),
    "Workforce churn": (
        "Recruitment cost per hire times attrition, onboarding, a productivity ramp of 4-12 "
        "weeks, backfill lag. Egyptian technical and contact-centre roles commonly run "
        "20-35% annual attrition."
    ),
    "Certification and compliance": (
        "Working at height, first aid, defensive driving, HV/LV electrical, OSHA or NEBOSH, "
        "vendor certifications, fibre splicing, ISO 27001 or PCI-DSS, regulator clearance "
        "for field staff. All recur."
    ),
    "Equipment upkeep": (
        "Calibration of test instruments per year, tool loss and breakage allowance, spares "
        "obsolescence write-off."
    ),
    "Financial costs": (
        "Performance bonds and advance payment guarantees, working capital from receivable "
        "days, FX hedging or an unhedged exposure allowance, SLA penalty expected value."
    ),
    "Lifecycle": (
        "Mobilisation (recruitment wave, initial training, tooling, transition from the "
        "incumbent), parallel run and knowledge transfer, demobilisation and exit. Amortise "
        "across the term and show separately."
    ),
}


#: Egypt-specific drivers that change the answer and that a generic interview misses.
#: Cost Driver Library, Part 5, plus the Ramadan productivity rule from Step 3.
EGYPT_NOTES = (
    "Ramadan is a cost event twice over: media rates rise sharply for the window and the "
    "best inventory is committed months ahead, while delivery productivity falls by roughly "
    "25% for about 29 days. Never smooth either across the year.\n"
    "Islamic holidays move about 11 days earlier each Gregorian year, so a calendar cannot "
    "be reused from last year's model.\n"
    "Arabic versioning is a count of versions, not of assets: Egyptian dialect, Modern "
    "Standard Arabic and Gulf variants are separate deliverables.\n"
    "Pan-Arab talent and imported goods price in hard currency and escalate on the FX path, "
    "not on local CPI.\n"
    "Public-location shooting and governorate permits carry real lead times that belong in "
    "the schedule as well as the cost.\n"
    "Density beats volume: 500 sites in one governorate cost far less per site than 500 "
    "across eight. Always capture the geographic split, never just the total."
)
